/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package practico4;

import java.util.HashSet;

/**
 *
 * @author Ivan
 */
public class Colegio extends javax.swing.JFrame {
    
    /**
     * Creates new form JFmain
     */
    
    public static final HashSet<Materia> materias = new HashSet();
    public static final HashSet<Alumno> alumnos = new HashSet();
    
    public Colegio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu = new javax.swing.JMenu();
        miMaterias = new javax.swing.JMenuItem();
        miAlumnos = new javax.swing.JMenuItem();
        miInscripcion = new javax.swing.JMenuItem();
        miSalir = new javax.swing.JMenuItem();

        jButton1.setText("jButton1");

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("jRadioButtonMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 539, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 409, Short.MAX_VALUE)
        );

        jMenuBar1.setBackground(new java.awt.Color(51, 51, 51));

        jMenu.setBackground(new java.awt.Color(51, 51, 51));
        jMenu.setText("Menu");

        miMaterias.setText("Materias");
        miMaterias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miMateriasActionPerformed(evt);
            }
        });
        jMenu.add(miMaterias);

        miAlumnos.setText("Alumnos");
        miAlumnos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miAlumnosActionPerformed(evt);
            }
        });
        jMenu.add(miAlumnos);

        miInscripcion.setText("Inscripcion");
        miInscripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miInscripcionActionPerformed(evt);
            }
        });
        jMenu.add(miInscripcion);

        miSalir.setText("Salir");
        miSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miSalirActionPerformed(evt);
            }
        });
        jMenu.add(miSalir);

        jMenuBar1.add(jMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void miMateriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miMateriasActionPerformed
        jDesktopPane1.removeAll();
        jDesktopPane1.repaint();
        FriMaterias friMaterias = new FriMaterias();
        friMaterias.setVisible(true);
        jDesktopPane1.add(friMaterias);
    }//GEN-LAST:event_miMateriasActionPerformed

    private void miAlumnosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miAlumnosActionPerformed
        jDesktopPane1.removeAll();
        jDesktopPane1.repaint();
        FriAlumnos friAlumnos = new FriAlumnos();
        friAlumnos.setVisible(true);
        jDesktopPane1.add(friAlumnos);
    }//GEN-LAST:event_miAlumnosActionPerformed

    private void miInscripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miInscripcionActionPerformed
        jDesktopPane1.removeAll();
        jDesktopPane1.repaint();
        FriInscripcion friInscripcion = new FriInscripcion();
        friInscripcion.setVisible(true);
        jDesktopPane1.add(friInscripcion);
    }//GEN-LAST:event_miInscripcionActionPerformed

    private void miSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miSalirActionPerformed
       System.exit(0);
    }//GEN-LAST:event_miSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Colegio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Colegio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Colegio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Colegio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Colegio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenu jMenu;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JMenuItem miAlumnos;
    private javax.swing.JMenuItem miInscripcion;
    private javax.swing.JMenuItem miMaterias;
    private javax.swing.JMenuItem miSalir;
    // End of variables declaration//GEN-END:variables
}
