/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package practico4;

import javax.swing.JOptionPane;

/**
 *
 * @author Martin
 */
public class FriAlumnos extends javax.swing.JInternalFrame {

    /**
     * Creates new form JIForm
     */
    public FriAlumnos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        butGuardarAlumno = new javax.swing.JButton();
        butSalirAlumno = new javax.swing.JButton();
        txtFormMateria = new javax.swing.JLabel();
        txtApellido = new javax.swing.JLabel();
        txtNombre = new javax.swing.JLabel();
        txtLegajo2 = new javax.swing.JLabel();
        tfLegajo = new javax.swing.JTextField();
        tfApellido = new javax.swing.JTextField();
        tfNombre = new javax.swing.JTextField();
        butNuevoAlumno = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        butGuardarAlumno.setBackground(new java.awt.Color(51, 51, 51));
        butGuardarAlumno.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        butGuardarAlumno.setText("Guardar");
        butGuardarAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butGuardarAlumnoAlumnoActionPerformed(evt);
            }
        });

        butSalirAlumno.setBackground(new java.awt.Color(51, 51, 51));
        butSalirAlumno.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        butSalirAlumno.setText("Salir");
        butSalirAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butSalirAlumnoAlumnoActionPerformed(evt);
            }
        });

        txtFormMateria.setBackground(new java.awt.Color(255, 255, 255));
        txtFormMateria.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        txtFormMateria.setForeground(new java.awt.Color(255, 255, 255));
        txtFormMateria.setText("Formulario de Alumnos");
        txtFormMateria.setToolTipText("");
        txtFormMateria.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        txtApellido.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        txtApellido.setForeground(new java.awt.Color(255, 255, 255));
        txtApellido.setText("Apellido:");

        txtNombre.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        txtNombre.setForeground(new java.awt.Color(255, 255, 255));
        txtNombre.setText("Nombre:");

        txtLegajo2.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        txtLegajo2.setForeground(new java.awt.Color(255, 255, 255));
        txtLegajo2.setText("Legajo:");

        tfLegajo.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        tfLegajo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfLegajoActionPerformed(evt);
            }
        });

        tfApellido.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        tfApellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfApellidoActionPerformed(evt);
            }
        });

        tfNombre.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        tfNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNombreActionPerformed(evt);
            }
        });

        butNuevoAlumno.setBackground(new java.awt.Color(51, 51, 51));
        butNuevoAlumno.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        butNuevoAlumno.setText("Nuevo");
        butNuevoAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butNuevoAlumnoAlumnoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(txtFormMateria)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(tfNombre))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(tfApellido)))
                            .addGap(180, 180, 180))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(txtLegajo2, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(tfLegajo, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(19, 19, 19)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(butGuardarAlumno)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(butNuevoAlumno)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(butSalirAlumno)))
                .addGap(25, 25, 25))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtFormMateria, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtLegajo2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfLegajo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(butGuardarAlumno)
                    .addComponent(butNuevoAlumno)
                    .addComponent(butSalirAlumno))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void butSalirAlumnoAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butSalirAlumnoAlumnoActionPerformed
        dispose();
    }//GEN-LAST:event_butSalirAlumnoAlumnoActionPerformed

    private void butGuardarAlumnoAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butGuardarAlumnoAlumnoActionPerformed
        try {
            Colegio.alumnos.add(new Alumno(Integer.parseInt(tfLegajo.getText()), tfNombre.getText(), tfApellido.getText()));
            tfLegajo.setText("");
            tfNombre.setText("");
            tfApellido.setText("");
        } catch (NumberFormatException e) {
            tfLegajo.setText("");
            JOptionPane.showMessageDialog(null, "Error de tipeo. Caracter en campo numérico, vuelva a ingresar los datos");
        }
    }//GEN-LAST:event_butGuardarAlumnoAlumnoActionPerformed

    private void butNuevoAlumnoAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butNuevoAlumnoAlumnoActionPerformed
        tfLegajo.setText("");
        tfNombre.setText("");
        tfApellido.setText("");
    }//GEN-LAST:event_butNuevoAlumnoAlumnoActionPerformed

    private void tfNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNombreActionPerformed

    private void tfApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfApellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfApellidoActionPerformed

    private void tfLegajoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfLegajoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfLegajoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton butGuardarAlumno;
    private javax.swing.JButton butNuevoAlumno;
    private javax.swing.JButton butSalirAlumno;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField tfApellido;
    private javax.swing.JTextField tfLegajo;
    private javax.swing.JTextField tfNombre;
    private javax.swing.JLabel txtApellido;
    private javax.swing.JLabel txtFormMateria;
    private javax.swing.JLabel txtLegajo2;
    private javax.swing.JLabel txtNombre;
    // End of variables declaration//GEN-END:variables
}
